name: esp32 port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/esp32/**'

jobs:
  build_idf402:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: source tools/ci.sh && ci_esp32_idf402_setup
    - name: Build
      run: source tools/ci.sh && ci_esp32_build
    - uses: actions/upload-artifact@v3
      with:
        name: micropython402.bin
        path: ports/esp32/build-GENERIC/firmware.bin

  build_idf44:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: source tools/ci.sh && ci_esp32_idf44_setup
    - name: Build
      run: source tools/ci.sh && ci_esp32_build
    - uses: actions/upload-artifact@v3
      with:
        name: micropython44.bin
        path: ports/esp32/build-GENERIC/firmware.bin
